apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-hml                    # Nome da aplicação no Argo CD
  namespace: argocd                  # Namespace onde o Argo CD está instalado
spec:
  project: homolog                   # ALTERAÇÃO: evitar project default; usar projeto dedicado de homolog

  source:
    repoURL: https://github.com/brunobaltazar/kubernets_app_argo_cd.git  # Repositório Git com os manifests
    targetRevision: main                                                  # Para produção, prefira tag ou commit fixo
    path: nginx/hml                                                       # Caminho dentro do repositório
    directory:
      recurse: true                                                       # Aplica todos os YAMLs dentro da pasta

  destination:
    server: https://kubernetes.default.svc                                # Cluster local onde o Argo CD está rodando
    namespace: hml-nginx                                                  # Namespace dedicado da aplicação

  syncPolicy:
    automated:
      prune: true          # ALTERAÇÃO: como o namespace é dedicado, é melhor manter Git = cluster
      selfHeal: true       # Reaplica se houver drift manual no cluster

    syncOptions:
      - CreateNamespace=true  # Cria o namespace se ainda não existir